### ISSUE TITLE
Does it really need so many modules?

### ISSUE THREAD

**Issue by jjtbsomhorst** [jghaanstra/icalendar.homey#1]
I'm wondering. Does this app really nead this much nodemodules loaded?

**Comment by jghaanstra** [comment]
My app only requires one package but  ... 

https://i.redd.it/ndi4nd6i7k7z.png

**Comment by jjtbsomhorst** [comment]
Yeah I already thought so but It would be nice if you (or anyone else) could take a look and find out if it could be less package hell.
